#!/bin/bash

echo ""
echo "*** I M P O R T A N T :"
echo "when you build and install VisIt, be sure"
echo "to follow all steps, including the creation"
echo "of a distribution tarball, and its installation on your machine."
echo "DO NOT use directly the executables generated by the build script!"
echo "the xml2cmake paths will be wrong if you do it"
echo ""


if [ ! ${XML2CMAKE_BIN} ]; then
    echo ""
    echo "***please set XML2CMAKE_BIN environment variable"
    echo "***it should be something like /usr/local/visit/bin/xml2cmake"
    echo ""
    ERR=1
fi

if [ ! ${CMAKE_VISIT} ]; then
    echo ""
    echo "***please set CMAKE_VISIT environment variable"
    echo "***remember that VisIt is incompatible with cmake version 2.8.12"
    echo "***(use the cmake you used to compile VisIt)"
    echo ""
    ERR=1
fi

if [ ${ERR} ]; then
    exit -1
fi

if [ -f Makefile ]; then
    rm -f Makefile
fi
if [ -f CMakeLists.txt ]; then 
    rm -f CMakeLists.txt
fi
if [ -f cmake_install.cmake ]; then
    rm -f cmake_install.cmake
fi
if [ -d CMakeFiles ]; then
    rm -rf CMakeFiles
fi
if [ -f CMakeCache.txt ]; then
    rm -f CMakeCache.txt
fi
CURDIR=`pwd`
cd QHGsources
make clean
make
cd ${CURDIR}
${XML2CMAKE_BIN} qdf.xml
${CMAKE_VISIT} .
make

