/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <PieAttributes.h>
#include <DataNode.h>

//
// Enum conversion methods for PieAttributes::GlyphStyle
//

static const char *GlyphStyle_strings[] = {
"STYLE_PIE", "STYLE_STAR", "STYLE_BARS"
};

std::string
PieAttributes::GlyphStyle_ToString(PieAttributes::GlyphStyle t)
{
    int index = int(t);
    if(index < 0 || index >= 3) index = 0;
    return GlyphStyle_strings[index];
}

std::string
PieAttributes::GlyphStyle_ToString(int t)
{
    int index = (t < 0 || t >= 3) ? 0 : t;
    return GlyphStyle_strings[index];
}

bool
PieAttributes::GlyphStyle_FromString(const std::string &s, PieAttributes::GlyphStyle &val)
{
    val = PieAttributes::STYLE_PIE;
    for(int i = 0; i < 3; ++i)
    {
        if(s == GlyphStyle_strings[i])
        {
            val = (GlyphStyle)i;
            return true;
        }
    }
    return false;
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose: 
//   Init utility for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void PieAttributes::Init()
{
    iGlyphStyle = STYLE_PIE;
    fScale1 = 1;
    fScale2 = 1;
    bFramed = true;

    PieAttributes::SelectAll();
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose: 
//   Copy utility for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void PieAttributes::Copy(const PieAttributes &obj)
{
    iGlyphStyle = obj.iGlyphStyle;
    fScale1 = obj.fScale1;
    fScale2 = obj.fScale2;
    bFramed = obj.bFramed;

    PieAttributes::SelectAll();
}

// Type map format string
const char *PieAttributes::TypeMapFormatString = PIEATTRIBUTES_TMFS;
const AttributeGroup::private_tmfs_t PieAttributes::TmfsStruct = {PIEATTRIBUTES_TMFS};


// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose: 
//   Default constructor for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

PieAttributes::PieAttributes() : 
    AttributeSubject(PieAttributes::TypeMapFormatString)
{
    PieAttributes::Init();
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose: 
//   Constructor for the derived classes of PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

PieAttributes::PieAttributes(private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    PieAttributes::Init();
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose: 
//   Copy constructor for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

PieAttributes::PieAttributes(const PieAttributes &obj) : 
    AttributeSubject(PieAttributes::TypeMapFormatString)
{
    PieAttributes::Copy(obj);
}

// ****************************************************************************
// Method: PieAttributes::PieAttributes
//
// Purpose: 
//   Copy constructor for derived classes of the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

PieAttributes::PieAttributes(const PieAttributes &obj, private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    PieAttributes::Copy(obj);
}

// ****************************************************************************
// Method: PieAttributes::~PieAttributes
//
// Purpose: 
//   Destructor for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

PieAttributes::~PieAttributes()
{
    // nothing here
}

// ****************************************************************************
// Method: PieAttributes::operator = 
//
// Purpose: 
//   Assignment operator for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

PieAttributes& 
PieAttributes::operator = (const PieAttributes &obj)
{
    if (this == &obj) return *this;

    PieAttributes::Copy(obj);

    return *this;
}

// ****************************************************************************
// Method: PieAttributes::operator == 
//
// Purpose: 
//   Comparison operator == for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
PieAttributes::operator == (const PieAttributes &obj) const
{
    // Create the return value
    return ((iGlyphStyle == obj.iGlyphStyle) &&
            (fScale1 == obj.fScale1) &&
            (fScale2 == obj.fScale2) &&
            (bFramed == obj.bFramed));
}

// ****************************************************************************
// Method: PieAttributes::operator != 
//
// Purpose: 
//   Comparison operator != for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
PieAttributes::operator != (const PieAttributes &obj) const
{
    return !(this->operator == (obj));
}

// ****************************************************************************
// Method: PieAttributes::TypeName
//
// Purpose: 
//   Type name method for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

const std::string
PieAttributes::TypeName() const
{
    return "PieAttributes";
}

// ****************************************************************************
// Method: PieAttributes::CopyAttributes
//
// Purpose: 
//   CopyAttributes method for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
PieAttributes::CopyAttributes(const AttributeGroup *atts)
{
    if(TypeName() != atts->TypeName())
        return false;

    // Call assignment operator.
    const PieAttributes *tmp = (const PieAttributes *)atts;
    *this = *tmp;

    return true;
}

// ****************************************************************************
// Method: PieAttributes::CreateCompatible
//
// Purpose: 
//   CreateCompatible method for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
PieAttributes::CreateCompatible(const std::string &tname) const
{
    AttributeSubject *retval = 0;
    if(TypeName() == tname)
        retval = new PieAttributes(*this);
    // Other cases could go here too. 

    return retval;
}

// ****************************************************************************
// Method: PieAttributes::NewInstance
//
// Purpose: 
//   NewInstance method for the PieAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
PieAttributes::NewInstance(bool copy) const
{
    AttributeSubject *retval = 0;
    if(copy)
        retval = new PieAttributes(*this);
    else
        retval = new PieAttributes;

    return retval;
}

// ****************************************************************************
// Method: PieAttributes::SelectAll
//
// Purpose: 
//   Selects all attributes.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
PieAttributes::SelectAll()
{
    Select(ID_iGlyphStyle, (void *)&iGlyphStyle);
    Select(ID_fScale1,     (void *)&fScale1);
    Select(ID_fScale2,     (void *)&fScale2);
    Select(ID_bFramed,     (void *)&bFramed);
}

///////////////////////////////////////////////////////////////////////////////
// Persistence methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: PieAttributes::CreateNode
//
// Purpose: 
//   This method creates a DataNode representation of the object so it can be saved to a config file.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
PieAttributes::CreateNode(DataNode *parentNode, bool completeSave, bool forceAdd)
{
    if(parentNode == 0)
        return false;

    PieAttributes defaultObject;
    bool addToParent = false;
    // Create a node for PieAttributes.
    DataNode *node = new DataNode("PieAttributes");

    if(completeSave || !FieldsEqual(ID_iGlyphStyle, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("iGlyphStyle", GlyphStyle_ToString(iGlyphStyle)));
    }

    if(completeSave || !FieldsEqual(ID_fScale1, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fScale1", fScale1));
    }

    if(completeSave || !FieldsEqual(ID_fScale2, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("fScale2", fScale2));
    }

    if(completeSave || !FieldsEqual(ID_bFramed, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("bFramed", bFramed));
    }


    // Add the node to the parent node.
    if(addToParent || forceAdd)
        parentNode->AddNode(node);
    else
        delete node;

    return (addToParent || forceAdd);
}

// ****************************************************************************
// Method: PieAttributes::SetFromNode
//
// Purpose: 
//   This method sets attributes in this object from values in a DataNode representation of the object.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
PieAttributes::SetFromNode(DataNode *parentNode)
{
    if(parentNode == 0)
        return;

    DataNode *searchNode = parentNode->GetNode("PieAttributes");
    if(searchNode == 0)
        return;

    DataNode *node;
    if((node = searchNode->GetNode("iGlyphStyle")) != 0)
    {
        // Allow enums to be int or string in the config file
        if(node->GetNodeType() == INT_NODE)
        {
            int ival = node->AsInt();
            if(ival >= 0 && ival < 3)
                SetIGlyphStyle(GlyphStyle(ival));
        }
        else if(node->GetNodeType() == STRING_NODE)
        {
            GlyphStyle value;
            if(GlyphStyle_FromString(node->AsString(), value))
                SetIGlyphStyle(value);
        }
    }
    if((node = searchNode->GetNode("fScale1")) != 0)
        SetFScale1(node->AsFloat());
    if((node = searchNode->GetNode("fScale2")) != 0)
        SetFScale2(node->AsFloat());
    if((node = searchNode->GetNode("bFramed")) != 0)
        SetBFramed(node->AsBool());
}

///////////////////////////////////////////////////////////////////////////////
// Set property methods
///////////////////////////////////////////////////////////////////////////////

void
PieAttributes::SetIGlyphStyle(PieAttributes::GlyphStyle iGlyphStyle_)
{
    iGlyphStyle = iGlyphStyle_;
    Select(ID_iGlyphStyle, (void *)&iGlyphStyle);
}

void
PieAttributes::SetFScale1(float fScale1_)
{
    fScale1 = fScale1_;
    Select(ID_fScale1, (void *)&fScale1);
}

void
PieAttributes::SetFScale2(float fScale2_)
{
    fScale2 = fScale2_;
    Select(ID_fScale2, (void *)&fScale2);
}

void
PieAttributes::SetBFramed(bool bFramed_)
{
    bFramed = bFramed_;
    Select(ID_bFramed, (void *)&bFramed);
}

///////////////////////////////////////////////////////////////////////////////
// Get property methods
///////////////////////////////////////////////////////////////////////////////

PieAttributes::GlyphStyle
PieAttributes::GetIGlyphStyle() const
{
    return GlyphStyle(iGlyphStyle);
}

float
PieAttributes::GetFScale1() const
{
    return fScale1;
}

float
PieAttributes::GetFScale2() const
{
    return fScale2;
}

bool
PieAttributes::GetBFramed() const
{
    return bFramed;
}

///////////////////////////////////////////////////////////////////////////////
// Keyframing methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: PieAttributes::GetFieldName
//
// Purpose: 
//   This method returns the name of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
PieAttributes::GetFieldName(int index) const
{
    switch (index)
    {
    case ID_iGlyphStyle: return "iGlyphStyle";
    case ID_fScale1:     return "fScale1";
    case ID_fScale2:     return "fScale2";
    case ID_bFramed:     return "bFramed";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: PieAttributes::GetFieldType
//
// Purpose: 
//   This method returns the type of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeGroup::FieldType
PieAttributes::GetFieldType(int index) const
{
    switch (index)
    {
    case ID_iGlyphStyle: return FieldType_enum;
    case ID_fScale1:     return FieldType_float;
    case ID_fScale2:     return FieldType_float;
    case ID_bFramed:     return FieldType_bool;
    default:  return FieldType_unknown;
    }
}

// ****************************************************************************
// Method: PieAttributes::GetFieldTypeName
//
// Purpose: 
//   This method returns the name of a field type given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
PieAttributes::GetFieldTypeName(int index) const
{
    switch (index)
    {
    case ID_iGlyphStyle: return "enum";
    case ID_fScale1:     return "float";
    case ID_fScale2:     return "float";
    case ID_bFramed:     return "bool";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: PieAttributes::FieldsEqual
//
// Purpose: 
//   This method compares two fields and return true if they are equal.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
PieAttributes::FieldsEqual(int index_, const AttributeGroup *rhs) const
{
    const PieAttributes &obj = *((const PieAttributes*)rhs);
    bool retval = false;
    switch (index_)
    {
    case ID_iGlyphStyle:
        {  // new scope
        retval = (iGlyphStyle == obj.iGlyphStyle);
        }
        break;
    case ID_fScale1:
        {  // new scope
        retval = (fScale1 == obj.fScale1);
        }
        break;
    case ID_fScale2:
        {  // new scope
        retval = (fScale2 == obj.fScale2);
        }
        break;
    case ID_bFramed:
        {  // new scope
        retval = (bFramed == obj.bFramed);
        }
        break;
    default: retval = false;
    }

    return retval;
}

///////////////////////////////////////////////////////////////////////////////
// User-defined methods.
///////////////////////////////////////////////////////////////////////////////

//--------------------------------------------------------------------
// ChangesRequireRecalculation
//   check if a attribute has changed which requires a recalculation.
//   currently, only changes in fScale1 entail recalculation
//
bool
PieAttributes::ChangesRequireRecalculation(const PieAttributes &obj)
{
    // dummy test to see if it works 
        printf("obj (cur): scale1 %f (%f), scale2 %f (%f)\n", obj.fScale1, fScale1, obj.fScale2, fScale2);
    return (fScale1 != obj.fScale1);
}

