/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include "QvisPiePlotWindow.h"

#include <PieAttributes.h>
#include <ViewerProxy.h>

#include <QCheckBox>
#include <QLabel>
#include <QLayout>
#include <QLineEdit>
#include <QSpinBox>
#include <QButtonGroup>
#include <QRadioButton>
#include <QvisColorTableButton.h>
#include <QvisOpacitySlider.h>
#include <QvisColorButton.h>
#include <QvisLineStyleWidget.h>
#include <QvisLineWidthWidget.h>
#include <QvisVariableButton.h>

#include <QTimer>

#include <PlotInfoAttributes.h>

#include <stdio.h>
#include <string>

using std::string;

// ****************************************************************************
// Method: QvisPiePlotWindow::QvisPiePlotWindow
//
// Purpose: 
//   Constructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisPiePlotWindow::QvisPiePlotWindow(const int type,
                         PieAttributes *subj,
                         const QString &caption,
                         const QString &shortName,
                         QvisNotepadArea *notepad)
    : QvisPostableWindowObserver(subj, caption, shortName, notepad)
{
    plotType = type;
    atts = subj;

    /*
    PlotInfoAttributes *pia =  GetViewerState()->GetPlotInformation(plotType);
    MapNode *pMNode = pia->GetData().GetEntry("PieInfo");
    if (pMNode != NULL)  {
        MapNode &vPie = *pMNode;
        
        float fNewScale1 = vPie["Pie_Scale1"].AsFloat();
        printf("Received scale: %f\n", fNewScale1);
        if (fNewScale1 > 0)
        {
            if(fNewScale1 != atts->GetFScale1())
            {
                // The new scale is different. Set it and Apply so the viewer gets it.
                atts->SetFScale1(fNewScale1);
                Apply();
                vPie["Pie_Scale1"] = -1;
            }
        }
    }
    */
    
    // watch plot info
    printf("Attaching plot type %d, subject %p\n", plotType, GetViewerState()->GetPlotInformation(plotType));
    GetViewerState()->GetPlotInformation(plotType)->Attach(this);
    
}


// ****************************************************************************
// Method: QvisPiePlotWindow::~QvisPiePlotWindow
//
// Purpose: 
//   Destructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisPiePlotWindow::~QvisPiePlotWindow()
{
    printf("Detaching plot type %d, subject %p\n", plotType, GetViewerState()->GetPlotInformation(plotType));
    GetViewerState()->GetPlotInformation(plotType)->Detach(this);
}


// ****************************************************************************
// Method: QvisPiePlotWindow::CreateWindowContents
//
// Purpose: 
//   Creates the widgets for the window.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPiePlotWindow::CreateWindowContents()
{
    QGridLayout *mainLayout = new QGridLayout(0);
    topLayout->addLayout(mainLayout);

    iGlyphStyleLabel = new QLabel(tr("Glyph Style"), central);
    mainLayout->addWidget(iGlyphStyleLabel,0,0);
    iGlyphStyle = new QWidget(central);
    iGlyphStyleButtonGroup= new QButtonGroup(iGlyphStyle);
    QHBoxLayout *iGlyphStyleLayout = new QHBoxLayout(iGlyphStyle);
    iGlyphStyleLayout->setMargin(0);
    iGlyphStyleLayout->setSpacing(10);
    QRadioButton *iGlyphStyleGlyphStyleSTYLE_PIE = new QRadioButton(tr("STYLE_PIE"), iGlyphStyle);
    iGlyphStyleButtonGroup->addButton(iGlyphStyleGlyphStyleSTYLE_PIE,0);
    iGlyphStyleLayout->addWidget(iGlyphStyleGlyphStyleSTYLE_PIE);
    QRadioButton *iGlyphStyleGlyphStyleSTYLE_STAR = new QRadioButton(tr("STYLE_STAR"), iGlyphStyle);
    iGlyphStyleButtonGroup->addButton(iGlyphStyleGlyphStyleSTYLE_STAR,1);
    iGlyphStyleLayout->addWidget(iGlyphStyleGlyphStyleSTYLE_STAR);
    QRadioButton *iGlyphStyleGlyphStyleSTYLE_BARS = new QRadioButton(tr("STYLE_BARS"), iGlyphStyle);
    iGlyphStyleButtonGroup->addButton(iGlyphStyleGlyphStyleSTYLE_BARS,2);
    iGlyphStyleLayout->addWidget(iGlyphStyleGlyphStyleSTYLE_BARS);
    connect(iGlyphStyleButtonGroup, SIGNAL(buttonClicked(int)),
            this, SLOT(iGlyphStyleChanged(int)));
    mainLayout->addWidget(iGlyphStyle, 0,1);

    fScale1Label = new QLabel(tr("scale 1"), central);
    mainLayout->addWidget(fScale1Label,1,0);
    fScale1 = new QLineEdit(central);
    connect(fScale1, SIGNAL(returnPressed()),
            this, SLOT(fScale1ProcessText()));
    mainLayout->addWidget(fScale1, 1,1);

    fScale2Label = new QLabel(tr("scale 2"), central);
    mainLayout->addWidget(fScale2Label,2,0);
    fScale2 = new QLineEdit(central);
    connect(fScale2, SIGNAL(returnPressed()),
            this, SLOT(fScale2ProcessText()));
    mainLayout->addWidget(fScale2, 2,1);

    bFramed = new QCheckBox(tr("frame"), central);
    connect(bFramed, SIGNAL(toggled(bool)),
            this, SLOT(bFramedChanged(bool)));
    mainLayout->addWidget(bFramed, 3,0);

}


// ****************************************************************************
// Method: QvisPiePlotWindow::UpdateWindow
//
// Purpose: 
//   Updates the widgets in the window when the subject changes.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPiePlotWindow::UpdateWindow(bool doAll)
{
    std::cout << "[QvisPiePlotWindow::UpdateWindow("<<doAll<<")]: plotType: "<<plotType << endl;
std::cout << "selected subject " << SelectedSubject() << endl;
std::cout << "viewer subject " << GetViewerState()->GetPlotInformation(plotType) << endl;

/*
    if(SelectedSubject() == GetViewerState()->GetPlotInformation(plotType)) {
*/
        // update the plot attributes from the plot information but do it later when
        printf("do the single shot\n");
        // we get back to the event loop.
        UpdateUsingPlotInformation();
        atts->SelectField(PieAttributes::ID_fScale1);
        //        QTimer::singleShot(100, this, SLOT(UpdateUsingPlotInformation()));
        /*
    } else {
*/
        for(int i = 0; i < atts->NumAttributes(); ++i) {
            if(!doAll) {
                if(!atts->IsSelected(i)) {
                    continue;
                }
            }
            
            switch(i) {
            case PieAttributes::ID_iGlyphStyle:
                iGlyphStyleButtonGroup->blockSignals(true);
                if(iGlyphStyleButtonGroup->button((int)atts->GetIGlyphStyle()) != 0)
                    iGlyphStyleButtonGroup->button((int)atts->GetIGlyphStyle())->setChecked(true);
                iGlyphStyleButtonGroup->blockSignals(false);
                break;
            case PieAttributes::ID_fScale1:
                fScale1->setText(FloatToQString(atts->GetFScale1()));
                break;
            case PieAttributes::ID_fScale2:
                fScale2->setText(FloatToQString(atts->GetFScale2()));
                break;
            case PieAttributes::ID_bFramed:
                bFramed->blockSignals(true);
                bFramed->setChecked(atts->GetBFramed());
                bFramed->blockSignals(false);
                break;
            }
        }
        /*  }*/
}

// ****************************************************************************
// Method: QvisPiePlotWindow::GetCurrentValues
//
// New Qt slot
//                      UpdateUsingPlotInformation
void QvisPiePlotWindow::UpdateUsingPlotInformation()
{
    PlotInfoAttributes *pia =  GetViewerState()->GetPlotInformation(plotType);
    MapNode *pMNode = pia->GetData().GetEntry("PieInfo");
    if (pMNode != NULL)  {
        MapNode &vPie = *pMNode;
        
        float fNewScale1 = vPie["Pie_Scale1"].AsFloat();
        printf("Received scale: %f\n", fNewScale1);
        if (fNewScale1 > 0)
        {
            if(fNewScale1 != atts->GetFScale1())
            {
                // The new scale is different. Set it and Apply so the viewer gets it.
                atts->SetFScale1(fNewScale1);
                Apply();
                vPie["Pie_Scale1"] = -1;
            }
        }
    }
}
 


// ****************************************************************************
// Method: QvisPiePlotWindow::GetCurrentValues
//
// Purpose: 
//   Gets values from certain widgets and stores them in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPiePlotWindow::GetCurrentValues(int which_widget)
{
    bool doAll = (which_widget == -1);

    // Do fScale1
    if(which_widget == PieAttributes::ID_fScale1 || doAll)
    {
        float val;
        if(LineEditGetFloat(fScale1, val))
            atts->SetFScale1(val);
        else
        {
            ResettingError(tr("scale 1"),
                FloatToQString(atts->GetFScale1()));
            atts->SetFScale1(atts->GetFScale1());
        }
    }

    // Do fScale2
    if(which_widget == PieAttributes::ID_fScale2 || doAll)
    {
        float val;
        if(LineEditGetFloat(fScale2, val))
            atts->SetFScale2(val);
        else
        {
            ResettingError(tr("scale 2"),
                FloatToQString(atts->GetFScale2()));
            atts->SetFScale2(atts->GetFScale2());
        }
    }

}


// ****************************************************************************
// Method: QvisPiePlotWindow::Apply
//
// Purpose: 
//   Called to apply changes in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPiePlotWindow::Apply(bool ignore)
{
    if(AutoUpdate() || ignore)
    {
        GetCurrentValues(-1);
        atts->Notify();

        GetViewerMethods()->SetPlotOptions(plotType);
    }
    else
        atts->Notify();
}


//
// Qt Slot functions
//


// ****************************************************************************
// Method: QvisPiePlotWindow::apply
//
// Purpose: 
//   Qt slot function called when apply button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPiePlotWindow::apply()
{
    Apply(true);
}


// ****************************************************************************
// Method: QvisPiePlotWindow::makeDefault
//
// Purpose: 
//   Qt slot function called when "Make default" button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPiePlotWindow::makeDefault()
{
    GetCurrentValues(-1);
    atts->Notify();
    GetViewerMethods()->SetDefaultPlotOptions(plotType);
}


// ****************************************************************************
// Method: QvisPiePlotWindow::reset
//
// Purpose: 
//   Qt slot function called when reset button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPiePlotWindow::reset()
{
    GetViewerMethods()->ResetPlotOptions(plotType);
}


void
QvisPiePlotWindow::iGlyphStyleChanged(int val)
{
    if(val != atts->GetIGlyphStyle())
    {
        atts->SetIGlyphStyle(PieAttributes::GlyphStyle(val));
        SetUpdate(false);
        Apply();
    }
}


void
QvisPiePlotWindow::fScale1ProcessText()
{
    GetCurrentValues(PieAttributes::ID_fScale1);
    Apply();
}


void
QvisPiePlotWindow::fScale2ProcessText()
{
    GetCurrentValues(PieAttributes::ID_fScale2);
    Apply();
}


void
QvisPiePlotWindow::bFramedChanged(bool val)
{
    atts->SetBFramed(val);
    SetUpdate(false);
    Apply();
}


