/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                              avtPieFilter.C                              //
// ************************************************************************* //

#include <avtPieFilter.h>

#include <vtkDataSet.h>
#include <vtkPointData.h>
#include <DebugStream.h>


// ****************************************************************************
//  Method: avtPieFilter constructor
//
//  Programmer: jody -- generated by xml2avt
//  Creation:   Wed Mar 18 08:34:48 PDT 2015
//
// ****************************************************************************

avtPieFilter::avtPieFilter()
{
    debug1 << "[avtPieFilter::avtPieFilter()]" << endl;
}


// ****************************************************************************
//  Method: avtPieFilter destructor
//
//  Programmer: jody -- generated by xml2avt
//  Creation:   Wed Mar 18 08:34:48 PDT 2015
//
// ****************************************************************************

avtPieFilter::~avtPieFilter()
{
    debug1 << "[avtPieFilter::~avtPieFilter()]" << endl;
}


//@@ YOUR ROUTINES TO SET THE PARAMETERS OF THE FILTERS


// ****************************************************************************
//  Method: avtPieFilter::ExecuteData
//
//  Purpose:
//      Does the actual VTK code to modify the dataset.
//
//  Arguments:
//      inDS      The input dataset.
//      <unused>  The domain number.
//      <unused>  The label.
//
//  Returns:      The output dataset.
//
//  Programmer: jody -- generated by xml2avt
//  Creation:   Wed Mar 18 08:34:48 PDT 2015
//
// ****************************************************************************

vtkDataSet *
avtPieFilter::ExecuteData(vtkDataSet *inDS, int, std::string)
{
    //@@    THIS IS THE REAL VTK CODE
     PlotInfoAttributes pia = GetOutput()->GetInfo().GetAttributes().GetPlotInformation();
    MapNode *pMNode = pia.GetData().GetEntry("PieInfo");
    if (pMNode != NULL) {
        float fScale = inDS->GetLength()/66.0;
        MapNode &vPie = *pMNode;
        vPie["Pie_Scale1"] = fScale;
        printf("[avtPieFilter::ExecuteData] adding plot information (fScale:%f)\n", fScale);
        GetOutput()->GetInfo().GetAttributes().AddPlotInformation("PieInfo", vPie);

    }
 
    debug1 << "[avtPieFilter::ExecuteData(vtkDataSet *inDS, int, std::string)]" << endl;
    vtkPointData *pp = inDS->GetPointData();

    debug1 << "[avtPieFilter::ExecuteData(inDS)]: Num arrays" << pp->GetNumberOfArrays() << endl;
    debug1 << "[avtPieFilter::ExecuteData(inDS)]:     num components " << pp->GetNumberOfComponents() << endl;
    debug1 << "[avtPieFilter::ExecuteData(inDS)]:     num tuples "     << pp->GetNumberOfTuples() << endl;
    for (int i = 0; i < pp->GetNumberOfArrays(); ++i) {
        debug1 << "[avtPiePlotFilter::ExecuteData(inDS)]:   array[" << i << "]: " << pp->GetArrayName(i) << endl;
    }
    // trivial: out = in
    return inDS;
}


// ****************************************************************************
//  Method: avtPieFilter::UpdateDataObjectInfo
//
//  Purpose:
//      Allows the filter to change its output's data object information, which
//      is a description of the data object.
//
//  Programmer: jody -- generated by xml2avt
//  Creation:   Wed Mar 18 08:34:48 PDT 2015
//
// ****************************************************************************

void
avtPieFilter::UpdateDataObjectInfo(void)
{
    debug1 << "[avtPieFilter::UpdateDataObjectInfo()]" << endl;
    //@@    IF YOU SEE FUNNY THINGS WITH EXTENTS, ETC, YOU CAN CHANGE THAT HERE.
}
