/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                             avtPieRenderer.C                          //
// ************************************************************************* //


#include "avtPieRenderer.h"
#include <vtkDataSet.h>
#include <vtkPointData.h>
#include <DebugStream.h>

#include <vtkCellData.h>
#include <vtkDataArray.h>
#include <vtkSmartPointer.h>
#include <vtkUnsignedCharArray.h>

#include <GL/gl.h>
#include <GL/glut.h>

// ****************************************************************************
//  Method: avtPiePlot constructor
//
//  Programmer: jody -- generated by xml2avt
//  Creation:   Tue Mar 10 10:49:47 PDT 2015
//
// ****************************************************************************
avtPieRenderer::avtPieRenderer() 
    : avtCustomRenderer() {
    debug1 << "[avtPieRenderer::avtPieRenderer()]" << endl; 
    printf("[avtPieRenderer::avtPieRenderer()]\n");
    m_pPieMan = NULL;
}

// ****************************************************************************
//  Method: avtPiePlot constructor
//
//  Programmer: jody -- generated by xml2avt
//  Creation:   Tue Mar 10 10:49:47 PDT 2015
//
// ****************************************************************************
avtPieRenderer::~avtPieRenderer() {
    debug1 << "[avtPieRenderer::~avtPieRenderer()]" << endl; 
    printf("[avtPieRenderer::~avtPieRenderer()]\n");
    if (m_pPieMan != NULL) {
        delete m_pPieMan;
    }
}

// ****************************************************************************
//  Method: New
//
//  Programmer: jody 
//  Creation:   Tue Mar 10 10:49:47 PDT 2015
//
// ****************************************************************************
avtPieRenderer *avtPieRenderer::New(void) {
    debug1 << "[avtPieRenderer::New()]" << endl; 
    return new avtPieRenderer();
}
 
// Override this method to provide customized rendering
// functionality.
// ****************************************************************************
//  Method: Render
//
//  Programmer: jody 
//  Creation:   Tue Mar 10 10:49:47 PDT 2015
//
// ****************************************************************************
void avtPieRenderer::Render(vtkDataSet *ds) {
    
    if ((ds != NULL) && (m_pPieMan == NULL)){
        double dL = ds->GetLength()/66.0;
        ((PieAttributes *)pAtts)->SetFScale1(dL);
    }
    
    if (m_pPieMan == NULL) {
        printf("---------rebuild ------------\n");
        m_pPieMan = PieManager::createInstance(pAtts, ds);
    }
    if (m_pPieMan != NULL) {
        //  double dL = ds->GetLength()/25.0;
        //  ((PieAttributes *)pAtts)->SetFScale1(dL);
        //@@ do some rendering
        //        printf("scale 1: %f\n", pAtts->GetFScale1());
        m_pPieMan->drawPies();
    }



}
 
// Override this method so your renderer can release its
// graphical resources when instructed to do so.
// ****************************************************************************
//  Method: ReleaseGraphicsResources
//
//  Programmer: jody
//  Creation:   Tue Mar 10 10:49:47 PDT 2015
//
// ****************************************************************************
void avtPieRenderer::ReleaseGraphicsResources() {
    //@@ free any allocated resources?
    debug1 << "[avtPieRenderer::ReleaseGraphicsResources()]" << endl;

}
 
// Provide this method to set your renderer's attributes from
// avtPiePlot::SetAtts so your renderer can use data from
// the plot's state object.
// ****************************************************************************
//  Method: SetAtts
//
//  Programmer: jody 
//  Creation:   Tue Mar 10 10:49:47 PDT 2015
//
// ****************************************************************************
void avtPieRenderer::SetAtts(const AttributeGroup *pNewAtts) {
    debug1 << "[avtPieRenderer::SetAtts(const AttributeGroup *)]" << endl;
    printf("got new atts: %p\n", pNewAtts);
    pAtts = dynamic_cast<const PieAttributes *>(pNewAtts);
    if (m_pPieMan != NULL) {
        m_pPieMan->changeAttrs(pAtts);
    }
    //@@ recreate pies if necessary
    
}

// ****************************************************************************
//  Method: SetVariable
//
//  Programmer: jody 
//  Creation:   Tue Mar 10 10:49:47 PDT 2015
//
// ****************************************************************************
void avtPieRenderer::SetVariable(const char *name)
{
    //
    // If the variable is different then clear the flags indicating that
    // we have valid cached node and cell labels.
    //
    /*
    if(varname != 0 && name != 0 && strcmp(name, varname) != 0)
    {
        ClearLabelCaches();
    }
    */
    debug1 << "[avtPieRenderer::SetVariable(const char *name)]" << endl;
    debug1 << "[avtPieRenderer::SetVariable(const char *name)]: varname='" << name <<  "'" << endl;

    // Store the new variable name.
    delete [] varname;
    varname = new char[strlen(name) + 1];
    strcpy(varname, name);
}
